version: '3.8'

services:
  api:
    build: .
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=news_feed
      - ORIGINAL_API_BASE_URL=https://apisinhala.newsfirst.lk
      - NEWS_FETCH_INTERVAL=3600  # in seconds (1 hour)
    networks:
      - app_network

  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - app_network

  cloudflared:
    image: cloudflare/cloudflared:2025.1.0
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge